// an example for a wanted autogenerated file
package example_test

import (
	"database/sql"
	"fmt"
	"testing"

	"context"

	_ "github.com/mattn/go-sqlite3"
	"github.com/posener/orm"
	"github.com/posener/orm/example"
	porm "github.com/posener/orm/example/personsqlite3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var (
	p1 = example.Person{Name: "moshe", Age: 1}
	p2 = example.Person{Name: "haim", Age: 2}
	p3 = example.Person{Name: "zvika", Age: 3}
)

func TestPersonSelect(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := preparePerson(t)
	defer db.Close()

	res, err := db.Insert().SetName(p1.Name).SetAge(p1.Age).Exec(ctx)
	require.Nil(t, err, "Failed inserting")
	assertRowsAffected(t, 1, res)
	res, err = db.Insert().SetName(p2.Name).SetAge(p2.Age).Exec(ctx)
	require.Nil(t, err, "Failed inserting")
	assertRowsAffected(t, 1, res)
	res, err = db.InsertPerson(&p3).Exec(ctx)
	require.Nil(t, err, "Failed inserting")
	assertRowsAffected(t, 1, res)

	tests := []struct {
		q    porm.Querier
		want []example.Person
	}{
		{
			q:    db.Select(),
			want: []example.Person{p1, p2, p3},
		},
		{
			q:    db.Select().SelectName(),
			want: []example.Person{{Name: "moshe"}, {Name: "haim"}, {Name: "zvika"}},
		},
		{
			q:    db.Select().SelectAge(),
			want: []example.Person{{Age: 1}, {Age: 2}, {Age: 3}},
		},
		{
			q:    db.Select().SelectAge().SelectName(),
			want: []example.Person{p1, p2, p3},
		},
		{
			q:    db.Select().SelectName().SelectAge(),
			want: []example.Person{p1, p2, p3},
		},
		{
			q:    db.Select().Where(porm.WhereName(orm.OpEq, "moshe")),
			want: []example.Person{p1},
		},
		{
			q:    db.Select().Where(porm.WhereName(orm.OpEq, "moshe").Or(porm.WhereAge(orm.OpEq, 2))),
			want: []example.Person{p1, p2},
		},
		{
			q:    db.Select().Where(porm.WhereName(orm.OpEq, "moshe").And(porm.WhereAge(orm.OpEq, 1))),
			want: []example.Person{p1},
		},
		{
			q: db.Select().Where(porm.WhereName(orm.OpEq, "moshe").And(porm.WhereAge(orm.OpEq, 2))),
		},
		{
			q:    db.Select().Where(porm.WhereAge(orm.OpGE, 2)),
			want: []example.Person{p2, p3},
		},
		{
			q:    db.Select().Where(porm.WhereAge(orm.OpGt, 2)),
			want: []example.Person{p3},
		},
		{
			q:    db.Select().Where(porm.WhereAge(orm.OpLE, 2)),
			want: []example.Person{p1, p2},
		},
		{
			q:    db.Select().Where(porm.WhereAge(orm.OpLt, 2)),
			want: []example.Person{p1},
		},
		{
			q:    db.Select().Where(porm.WhereName(orm.OpNe, "moshe")),
			want: []example.Person{p2, p3},
		},
		{
			q:    db.Select().Where(porm.WhereNameIn("moshe", "haim")),
			want: []example.Person{p1, p2},
		},
		{
			q:    db.Select().Where(porm.WhereAgeBetween(0, 2)),
			want: []example.Person{p1, p2},
		},
		{
			q:    db.Select().Limit(2),
			want: []example.Person{p1, p2},
		},
		{
			q:    db.Select().Page(1, 1),
			want: []example.Person{p2},
		},
	}

	for _, tt := range tests {
		t.Run(fmt.Sprintf("%+v", tt.q), func(t *testing.T) {
			p, err := tt.q.Query(ctx)
			if err != nil {
				t.Error(err)
			}
			assert.Equal(t, tt.want, p)
		})
	}
}

func TestSimpleCRUD(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := preparePerson(t)
	defer db.Close()

	// prepareAll dataset
	for _, p := range []example.Person{p1, p2, p3} {
		res, err := db.InsertPerson(&p).Exec(ctx)
		require.Nil(t, err, "Failed inserting")
		assertRowsAffected(t, 1, res)
	}

	ps, err := db.Select().Query(ctx)
	require.Nil(t, err)
	assert.Equal(t, []example.Person{p1, p2, p3}, ps)

	// Test delete
	delete := db.Delete().Where(porm.WhereName(orm.OpEq, "moshe"))
	res, err := delete.Exec(ctx)
	require.Nil(t, err)
	assertRowsAffected(t, 1, res)
	ps, err = db.Select().Query(ctx)
	if err != nil {
		t.Fatal(err)
	}
	assert.Equal(t, []example.Person{p2, p3}, ps)
	ps, err = db.Select().Where(porm.WhereName(orm.OpEq, "moshe")).Query(ctx)
	require.Nil(t, err)
	assert.Equal(t, []example.Person(nil), ps)

	// Test Update
	update := db.Update().SetName("Jonney").Where(porm.WhereName(orm.OpEq, "zvika"))
	res, err = update.Exec(ctx)
	require.Nil(t, err)
	assertRowsAffected(t, 1, res)

	ps, err = db.Select().Where(porm.WhereName(orm.OpEq, "Jonney")).Query(ctx)
	require.Nil(t, err)
	assert.Equal(t, []example.Person{{Name: "Jonney", Age: 3}}, ps)
}

func TestCount(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := preparePerson(t)
	defer db.Close()

	for i := 0; i < 100; i++ {
		res, err := db.InsertPerson(&example.Person{Name: fmt.Sprintf("Jim %d", i), Age: i / 5}).Exec(ctx)
		require.Nil(t, err, "Failed inserting")
		assertRowsAffected(t, 1, res)
	}

	tests := []struct {
		q    porm.Counter
		want []porm.PersonCount
	}{
		{
			q:    db.Select(),
			want: []porm.PersonCount{{Count: 100}},
		},
		{
			q:    db.Select().Where(porm.WhereAge(orm.OpLt, 10)),
			want: []porm.PersonCount{{Count: 50}},
		},
		{
			q:    db.Select().SelectName().Where(porm.WhereAge(orm.OpLt, 10)),
			want: []porm.PersonCount{{Person: example.Person{Name: "Jim 49"}, Count: 50}},
		},
		{
			q: db.Select().SelectAge().GroupByAge().Where(porm.WhereAgeIn(1, 3, 12)),
			want: []porm.PersonCount{
				{Person: example.Person{Age: 1}, Count: 5},
				{Person: example.Person{Age: 3}, Count: 5},
				{Person: example.Person{Age: 12}, Count: 5},
			},
		},
		{
			q: db.Select().SelectAge().GroupByAge().Where(porm.WhereAgeIn(1, 3, 12)).OrderByAge(orm.Desc),
			want: []porm.PersonCount{
				{Person: example.Person{Age: 12}, Count: 5},
				{Person: example.Person{Age: 3}, Count: 5},
				{Person: example.Person{Age: 1}, Count: 5},
			},
		},
	}

	for _, tt := range tests {
		t.Run(fmt.Sprintf("%+v", tt.q), func(t *testing.T) {
			got, err := tt.q.Count(ctx)
			if err != nil {
				t.Error(err)
			}
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestNew(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db, err := sql.Open("sqlite3", ":memory:")
	require.Nil(t, err)
	orm := porm.New(db)
	if testing.Verbose() {
		orm.Logger(t.Logf)
	}
	_, err = orm.Create().Exec(ctx)
	require.Nil(t, err)
}

func assertRowsAffected(t *testing.T, wantRows int64, result sql.Result) {
	gotRows, err := result.RowsAffected()
	require.Nil(t, err)
	assert.Equal(t, wantRows, gotRows)
}

func preparePerson(t *testing.T) porm.API {
	t.Helper()
	ctx := context.Background()
	db, err := porm.Open(":memory:")
	require.Nil(t, err)
	if testing.Verbose() {
		db.Logger(t.Logf)
	}
	_, err = db.Create().Exec(ctx)
	require.Nil(t, err)

	return db
}
