sudo: required

language: go

go:
  - 1.9

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql

env:
  global:
    - TRAVIS=1
    - MYSQL_ADDR=root:@(127.0.0.1:3306)/
    - POSTGRES_ADDR=postgres://postgres:@127.0.0.1:5432/?sslmode=disable

before_install:
  - go get -u ./...
  - go get -u golang.org/x/tools/cmd/goimports
  - make gen-tests
  - go get -t ./...
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
