sudo: required

language: go

go:
  - 1.9

services:
  - mysql

env:
  global:
    - TRAVIS=1
    - MYSQL_ADDR=root:@(127.0.0.1:3306)/test

before_install:
  - go get -u ./...
  - go get -u github.com/UnnoTed/fileb0x
  - go get -u golang.org/x/tools/cmd/goimports
  - make tests
  - go get -t ./...
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
