sudo: required

language: go

go:
  - 1.9

services:
  - mysql

env:
  global:
    - TRAVIS=1
    - MYSQL_ADDR=travis:@(127.0.0.1:3306)/test

before_install:
  - go get -u -t ./...
  - go get -u github.com/UnnoTed/fileb0x
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
