// Package bookorm was auto-generated by github.com/posener/orm; DO NOT EDIT
package bookorm

import (
	"github.com/posener/orm/example"

	"database/sql"

	"github.com/posener/orm"
	"github.com/posener/orm/common"
	"github.com/posener/orm/dialect"
)

// table is SQL table name
const table = "book"

// createColumnsStatements are columns definitions in different dialects
var createColumnsStatements = map[string]string{
	"mysql":   "`id` INTEGER PRIMARY KEY AUTO_INCREMENT, `name` TEXT, `year` INTEGER, `authorid` INTEGER",
	"sqlite3": "'id' INTEGER PRIMARY KEY AUTOINCREMENT, 'name' TEXT, 'year' INTEGER, 'authorid' INTEGER",
}

// API is the interface of the ORM object
type API interface {
	Close() error
	Create() *CreateBuilder
	Select() *SelectBuilder
	Insert() *InsertBuilder
	Update() *UpdateBuilder
	Delete() *DeleteBuilder

	Logger(orm.Logger)
}

// Querier is the interface for a SELECT SQL statement
type Querier interface {
	Query() ([]example.Book, error)
}

// Counter is the interface for a SELECT SQL statement for counting purposes
type Counter interface {
	Count() ([]BookCount, error)
}

// Firster is the interface for a SELECT SQL statement for getting only the
// first item. if no item matches the query, an `orm.ErrNotFound` will be returned.
type Firster interface {
	First() (*example.Book, error)
}

// Open opens database connection
func Open(driverName, dataSourceName string) (API, error) {
	db, err := sql.Open(driverName, dataSourceName)
	if err != nil {
		return nil, err
	}
	d, err := dialect.New(driverName)
	if err != nil {
		return nil, err
	}
	return &conn{dialect: d, db: db}, nil
}

// New returns an conn object from a db instance
func New(driverName string, db orm.DB) (API, error) {
	d, err := dialect.New(driverName)
	if err != nil {
		return nil, err
	}
	return &conn{dialect: d, db: db}, nil
}

// Create returns a builder of an SQL CREATE statement
func (c *conn) Create() *CreateBuilder {
	return &CreateBuilder{
		params: common.CreateParams{
			Table:            table,
			ColumnsStatement: createColumnsStatements[c.dialect.Name()],
		},
		conn: c,
	}
}

// Select returns a builder of an SQL SELECT statement
func (c *conn) Select() *SelectBuilder {
	s := &SelectBuilder{
		params: common.SelectParams{Table: table},
		conn:   c,
	}
	s.params.Columns = &s.selector
	return s
}

// Insert returns a builder of an SQL INSERT statement
func (c *conn) Insert() *InsertBuilder {
	return &InsertBuilder{
		params: common.InsertParams{Table: table},
		conn:   c,
	}
}

// Update returns a builder of an SQL UPDATE statement
func (c *conn) Update() *UpdateBuilder {
	return &UpdateBuilder{
		params: common.UpdateParams{Table: table},
		conn:   c,
	}
}

// Delete returns a builder of an SQL DELETE statement
func (c *conn) Delete() *DeleteBuilder {
	return &DeleteBuilder{
		params: common.DeleteParams{Table: table},
		conn:   c,
	}
}

// InsertBook returns an SQL INSERT statement builder filled with values of a given object
func (b *InsertBuilder) InsertBook(p *example.Book) *InsertBuilder {
	b.params.Assignments.Add("name", p.Name)
	b.params.Assignments.Add("year", p.Year)
	b.params.Assignments.Add("authorid", p.AuthorID)
	return b
}

// UpdateBook update values for all struct fields
func (b *UpdateBuilder) UpdateBook(p *example.Book) *UpdateBuilder {
	b.params.Assignments.Add("name", p.Name)
	b.params.Assignments.Add("year", p.Year)
	b.params.Assignments.Add("authorid", p.AuthorID)
	return b
}

// SetName sets value for column name in the INSERT statement
func (b *InsertBuilder) SetName(value string) *InsertBuilder {
	b.params.Assignments.Add("name", value)
	return b
}

// SetName sets value for column name in the UPDATE statement
func (b *UpdateBuilder) SetName(value string) *UpdateBuilder {
	b.params.Assignments.Add("name", value)
	return b
}

// SetYear sets value for column year in the INSERT statement
func (b *InsertBuilder) SetYear(value int) *InsertBuilder {
	b.params.Assignments.Add("year", value)
	return b
}

// SetYear sets value for column year in the UPDATE statement
func (b *UpdateBuilder) SetYear(value int) *UpdateBuilder {
	b.params.Assignments.Add("year", value)
	return b
}

// SetAuthorID sets value for column authorid in the INSERT statement
func (b *InsertBuilder) SetAuthorID(value int64) *InsertBuilder {
	b.params.Assignments.Add("authorid", value)
	return b
}

// SetAuthorID sets value for column authorid in the UPDATE statement
func (b *UpdateBuilder) SetAuthorID(value int64) *UpdateBuilder {
	b.params.Assignments.Add("authorid", value)
	return b
}
