// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allsqlite3

import (
	"context"

	"github.com/posener/orm/example"
)

// API is the interface of the ORM object
type API interface {
	Close() error
	Create() *Create
	Select() *Select
	Insert() *Insert
	Update() *Update
	Delete() *Delete
	InsertAll(*example.All) *Insert
	UpdateAll(*example.All) *Update

	Logger(Logger)
}

// Querier is the interface for a SELECT SQL statement
type Querier interface {
	Query(context.Context) ([]example.All, error)
}

// Counter is the interface for a SELECT SQL statement for counting purposes
type Counter interface {
	Count(context.Context) ([]AllCount, error)
}

// check that ORM fulfill the API
var _ API = &ORM{}
