// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allsqlite3

type columns struct {
	SelectInt    bool
	SelectString bool
	SelectBool   bool
	SelectTime   bool
	SelectSelect bool

	count bool // used for sql COUNT(*) column
}

// String is the SQL representation of columns
func (c *columns) Columns() []string {
	var cols []string
	if c.SelectInt {
		cols = append(cols, "int")
	}
	if c.SelectString {
		cols = append(cols, "string")
	}
	if c.SelectBool {
		cols = append(cols, "bool")
	}
	if c.SelectTime {
		cols = append(cols, "time")
	}
	if c.SelectSelect {
		cols = append(cols, "select")
	}

	return cols
}

func (c *columns) Count() bool {
	return c.count
}

// selectAll returns true if no column was specifically selected
func (c *columns) selectAll() bool {
	return !c.SelectInt && !c.SelectString && !c.SelectBool && !c.SelectTime && !c.SelectSelect && !c.count
}
