// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allsqlite3

func (c *Create) String() string {
	return `CREATE TABLE 'all' ( 'int' INTEGER PRIMARY KEY AUTOINCREMENT, 'string' VARCHAR(100) NOT NULL, 'bool' BOOLEAN, 'time' TIMESTAMP, 'select' INTEGER )`
}
