// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allsqlite3

import (
	"time"

	"github.com/posener/orm/example"
)

// InsertAll creates an INSERT statement according to the given object
func (o *ORM) InsertAll(p *example.All) *Insert {
	i := o.Insert()
	i.internal.Assignments.Add("int", p.Int)
	i.internal.Assignments.Add("string", p.String)
	i.internal.Assignments.Add("bool", p.Bool)
	i.internal.Assignments.Add("time", p.Time)
	i.internal.Assignments.Add("select", p.Select)
	return i
}

// SetInt sets value for column int in the INSERT statement
func (i *Insert) SetInt(value int) *Insert {
	i.internal.Assignments.Add("int", value)
	return i
}

// SetString sets value for column string in the INSERT statement
func (i *Insert) SetString(value string) *Insert {
	i.internal.Assignments.Add("string", value)
	return i
}

// SetBool sets value for column bool in the INSERT statement
func (i *Insert) SetBool(value bool) *Insert {
	i.internal.Assignments.Add("bool", value)
	return i
}

// SetTime sets value for column time in the INSERT statement
func (i *Insert) SetTime(value time.Time) *Insert {
	i.internal.Assignments.Add("time", value)
	return i
}

// SetSelect sets value for column select in the INSERT statement
func (i *Insert) SetSelect(value int) *Insert {
	i.internal.Assignments.Add("select", value)
	return i
}
