// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allsqlite3

import (
	"github.com/posener/orm/dialect/sqlite3"
	"time"

	"github.com/posener/orm/example"
)

func (u *TUpdate) String() string {
	return sqlite3.Update(u.orm, u.assign, u.where)
}

// InsertAll creates an UPDATE statement according to the given object
func (o *ORM) UpdateAll(p *example.All) *TUpdate {
	u := o.Update()
	u.add("int", p.Int)
	u.add("string", p.String)
	u.add("bool", p.Bool)
	u.add("time", p.Time)
	u.add("select", p.Select)
	return u
}

// SetInt sets value for column int in the UPDATE statement
func (u *TUpdate) SetInt(value int) *TUpdate {
	return u.add("int", value)
}

// SetString sets value for column string in the UPDATE statement
func (u *TUpdate) SetString(value string) *TUpdate {
	return u.add("string", value)
}

// SetBool sets value for column bool in the UPDATE statement
func (u *TUpdate) SetBool(value bool) *TUpdate {
	return u.add("bool", value)
}

// SetTime sets value for column time in the UPDATE statement
func (u *TUpdate) SetTime(value time.Time) *TUpdate {
	return u.add("time", value)
}

// SetSelect sets value for column select in the UPDATE statement
func (u *TUpdate) SetSelect(value int) *TUpdate {
	return u.add("select", value)
}
