package common

// CreateParams holds parameters for an SQL CREATE statement
type CreateParams struct {
	Table string
	// ColumnsStatement is the statement that describes the table columns in the
	// SQL CREATE statement, it's value autogenerated.
	ColumnsStatement string
	IfNotExists      bool
}

// InsertParams holds parameters for an SQL INSERT statement
type InsertParams struct {
	Table       string
	Assignments Assignments
}

// SelectParams holds parameters for an SQL SELECT statement
type SelectParams struct {
	Table   string
	Columns Columner
	Where   StatementArger
	Groups  Groups
	Orders  Orders
	Page    Page
}

// DeleteParams holds parameters for an SQL DELETE statement
type DeleteParams struct {
	Table string
	Where StatementArger
}

// UpdateParams holds parameters for an SQL UPDATE statement
type UpdateParams struct {
	Table       string
	Assignments Assignments
	Where       StatementArger
}
