// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

type columns struct {
	SelectName bool
	SelectAge  bool

	count bool // used for sql COUNT(*) column
}

// String is the SQL representation of columns
func (c *columns) Columns() []string {
	var cols []string
	if c.SelectName {
		cols = append(cols, "name")
	}
	if c.SelectAge {
		cols = append(cols, "age")
	}

	return cols
}

func (c *columns) Count() bool {
	return c.count
}

// selectAll returns true if no column was specifically selected
func (c *columns) selectAll() bool {
	return !c.SelectName && !c.SelectAge && !c.count
}
