// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

import (
	"github.com/posener/orm/example"
)

// InsertPerson creates an INSERT statement according to the given object
func (o *ORM) InsertPerson(p *example.Person) *Insert {
	i := o.Insert()
	i.Assignments.Add("name", p.Name)
	i.Assignments.Add("age", p.Age)
	return i
}

// SetName sets value for column name in the INSERT statement
func (i *Insert) SetName(value string) *Insert {
	i.Assignments.Add("name", value)
	return i
}

// SetAge sets value for column age in the INSERT statement
func (i *Insert) SetAge(value int) *Insert {
	i.Assignments.Add("age", value)
	return i
}
