// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

import (
	"github.com/posener/orm/dialect/sqlite3"

	"github.com/posener/orm/example"
)

func (i *TInsert) String() string {
	return sqlite3.Insert(i.orm, i.assign)
}

// InsertPerson creates an INSERT statement according to the given object
func (o *ORM) InsertPerson(p *example.Person) *TInsert {
	i := o.Insert()
	i.add("name", p.Name)
	i.add("age", p.Age)
	return i
}

// SetName sets value for column name in the INSERT statement
func (i *TInsert) SetName(value string) *TInsert {
	return i.add("name", value)
}

// SetAge sets value for column age in the INSERT statement
func (i *TInsert) SetAge(value int) *TInsert {
	return i.add("age", value)
}
