// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

import (
	"github.com/posener/orm"
)

// Insert is a struct to hold information for an INSERT statement
type Insert struct {
	orm.Insert
	orm *ORM
}
