// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

// Op is an SQL comparison operation
type Op string

const (
	OpEq   = "="
	OpNe   = "<>"
	OpGt   = ">"
	OpGE   = ">="
	OpLt   = "<"
	OpLE   = "<="
	OpLike = "LIKE"
)
