// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

import (
	"github.com/posener/orm/dialect/sqlite3"

	"github.com/posener/orm/example"
)

func (u *TUpdate) String() string {
	return sqlite3.Update(u.orm, u.assign, u.where)
}

// InsertPerson creates an UPDATE statement according to the given object
func (o *ORM) UpdatePerson(p *example.Person) *TUpdate {
	u := o.Update()
	u.add("name", p.Name)
	u.add("age", p.Age)
	return u
}

// SetName sets value for column name in the UPDATE statement
func (u *TUpdate) SetName(value string) *TUpdate {
	return u.add("name", value)
}

// SetAge sets value for column age in the UPDATE statement
func (u *TUpdate) SetAge(value int) *TUpdate {
	return u.add("age", value)
}
