// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

import (
	"github.com/posener/orm/example"
)

// InsertPerson creates an UPDATE statement according to the given object
func (o *ORM) UpdatePerson(p *example.Person) *Update {
	u := o.Update()
	u.Assignments.Add("name", p.Name)
	u.Assignments.Add("age", p.Age)
	return u
}

// SetName sets value for column name in the UPDATE statement
func (u *Update) SetName(value string) *Update {
	u.Assignments.Add("name", value)
	return u
}

// SetAge sets value for column age in the UPDATE statement
func (u *Update) SetAge(value int) *Update {
	u.Assignments.Add("age", value)
	return u
}
