// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personsqlite3

import (
	"github.com/posener/orm"
)

// WhereName adds a condition on Name to the WHERE statement
func WhereName(op orm.Op, val string) orm.Where {
	return orm.NewWhere(op, "name", val)
}

// WhereNameIn adds an IN condition on Name to the WHERE statement
func WhereNameIn(vals ...string) orm.Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return orm.NewWhereIn("name", args...)
}

// WhereNameBetween adds a BETWEEN condition on Name to the WHERE statement
func WhereNameBetween(low, high string) orm.Where {
	return orm.NewWhereBetween("name", low, high)
}

// WhereAge adds a condition on Age to the WHERE statement
func WhereAge(op orm.Op, val int) orm.Where {
	return orm.NewWhere(op, "age", val)
}

// WhereAgeIn adds an IN condition on Age to the WHERE statement
func WhereAgeIn(vals ...int) orm.Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return orm.NewWhereIn("age", args...)
}

// WhereAgeBetween adds a BETWEEN condition on Age to the WHERE statement
func WhereAgeBetween(low, high int) orm.Where {
	return orm.NewWhereBetween("age", low, high)
}
