// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allorm

import (
	"fmt"

	"github.com/posener/orm/example"
)

// API is the interface of the ORM object
type API interface {
	Create() *TCreate
	Select() *TSelect
	Insert() *TInsert
	Update() *TUpdate
	Delete() *TDelete
	InsertAll(*example.All) *TInsert
	UpdateAll(*example.All) *TUpdate

	Logger(Logger)
}

// Querier is the interface for a SELECT SQL statement
type Querier interface {
	fmt.Stringer
	Query() ([]example.All, error)
}

// Counter is the interface for a SELECT SQL statement for counting purposes
type Counter interface {
	fmt.Stringer
	Count() ([]AllCount, error)
}
