// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allorm

type columns struct {
	SelectInt    bool
	SelectString bool
	SelectBool   bool
	SelectAuto   bool
	SelectTime   bool
	SelectSelect bool

	count bool // used for sql COUNT(*) column
}

// String is the SQL representation of columns
func (c columns) String() string {
	var s string
	if c.SelectInt {
		s += "`int`, "
	}
	if c.SelectString {
		s += "`string`, "
	}
	if c.SelectBool {
		s += "`bool`, "
	}
	if c.SelectAuto {
		s += "`auto`, "
	}
	if c.SelectTime {
		s += "`time`, "
	}
	if c.SelectSelect {
		s += "`select`, "
	}

	if c.count {
		s += "COUNT(*), "
	}
	if len(s) == 0 { // no specific column was selected
		return "*"
	}
	return s[:len(s)-2]
}

// selectAll returns true if no column was specifically selected
func (c *columns) selectAll() bool {
	return !c.SelectInt && !c.SelectString && !c.SelectBool && !c.SelectAuto && !c.SelectTime && !c.SelectSelect && !c.count
}
