// Autogenerated by github.com/posener/orm
package allorm

func (c TCreate) String() string {
	// Create statement has a line for each variable with it's name and it's type.
	return `CREATE TABLE all (
		int INT PRIMARY KEY,
		text VARCHAR(100),
		bool BOOLEAN
	)`
}
