// Autogenerated by github.com/posener/orm
package allorm

import (
	"database/sql"
	"log"
)

type TCreate struct{}

func Create() TCreate {
	return TCreate{}
}

func (c TCreate) String() string {
	return `CREATE TABLE all (
		string VARCHAR(100),
		int INT,
		bool BOOLEAN
	)`
}

// Create creates a table for All
func (t TCreate) Exec(db *sql.DB) error {
	stmt := t.String()
	log.Printf("Create: '%v'", stmt)
	_, err := db.Exec(stmt)
	return err
}
