// Autogenerated by github.com/posener/orm; DO NOT EDIT
package allorm

// String returns the SQL DELETE statement string
func (s *TDelete) String() string {
	return "DELETE FROM 'all' " + s.where.String()
}
