// Autogenerated by github.com/posener/orm
package allorm

// Op is an SQL operation
type Op string

const (
	OpEq      = "="
	OpNe      = "<>"
	OpGt      = ">"
	OpGE      = ">="
	OpLt      = "<"
	OpLE      = "<="
	OpBetween = "BETWEEN"
	OpLike    = "LIKE"
	OpIn      = "IN"
)
