// Autogenerated by github.com/posener/orm
package allorm

// TSelect is the struct that holds the SELECT data
type TSelect struct {
	// Querier // TSelect is a querier, but this interface is autogenerated
	orm *ORM
	columns
	where *Where
	groupBy
	page Page
}

// Where applies where conditions on the query
func (s *TSelect) Where(where *Where) *TSelect {
	s.where = where
	return s
}

// Limit applies rows limit on the query response
func (s *TSelect) Limit(limit int64) *TSelect {
	s.page.limit = limit
	return s
}

// Page applies rows offset and limit on the query response
func (s *TSelect) Page(offset, limit int64) *TSelect {
	s.page.offset = offset
	s.page.limit = limit
	return s
}
