// Autogenerated by github.com/posener/orm
package allorm

import "github.com/posener/orm/example"

// Int Add Int to the selected column of a query
func (s TSelect) Int() TSelect {
	return append(s, "int")
}

// Text Add Text to the selected column of a query
func (s TSelect) Text() TSelect {
	return append(s, "text")
}

// Bool Add Bool to the selected column of a query
func (s TSelect) Bool() TSelect {
	return append(s, "bool")
}

// scanArgs are list of fields to be given to the sql Scan command
func (s TSelect) scanArgs(p *example.All) []interface{} {
	if len(s) == 0 {
		// add to args all the fields of p
		return []interface{}{
			&p.Int,
			&p.Text,
			&p.Bool,
		}
	}

	// select was given, choose only some fields
	m := make(map[string]int, len(s))
	for i, col := range s {
		m[col] = i + 1
	}
	args := make([]interface{}, len(s))
	if i := m["int"]; i != 0 {
		args[i-1] = &p.Int
	}
	if i := m["text"]; i != 0 {
		args[i-1] = &p.Text
	}
	if i := m["bool"]; i != 0 {
		args[i-1] = &p.Bool
	}
	return args
}
