// Autogenerated by github.com/posener/orm
package allorm

import (
	"time"
)

// WhereInt adds a condition on Int to the WHERE statement
func WhereInt(op Op, val int) *Where {
	return newWhere(op, "int", val)
}

// WhereIntIn adds an IN condition on Int to the WHERE statement
func WhereIntIn(vals ...int) *Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newWhereIn("int", args...)
}

// WhereIntBetween adds a BETWEEN condition on Int to the WHERE statement
func WhereIntBetween(low, high int) *Where {
	return newWhereBetween("int", low, high)
}

// WhereString adds a condition on String to the WHERE statement
func WhereString(op Op, val string) *Where {
	return newWhere(op, "string", val)
}

// WhereStringIn adds an IN condition on String to the WHERE statement
func WhereStringIn(vals ...string) *Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newWhereIn("string", args...)
}

// WhereStringBetween adds a BETWEEN condition on String to the WHERE statement
func WhereStringBetween(low, high string) *Where {
	return newWhereBetween("string", low, high)
}

// WhereBool adds a condition on Bool to the WHERE statement
func WhereBool(op Op, val bool) *Where {
	return newWhere(op, "bool", val)
}

// WhereBoolIn adds an IN condition on Bool to the WHERE statement
func WhereBoolIn(vals ...bool) *Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newWhereIn("bool", args...)
}

// WhereBoolBetween adds a BETWEEN condition on Bool to the WHERE statement
func WhereBoolBetween(low, high bool) *Where {
	return newWhereBetween("bool", low, high)
}

// WhereTime adds a condition on Time to the WHERE statement
func WhereTime(op Op, val time.Time) *Where {
	return newWhere(op, "time", val)
}

// WhereTimeIn adds an IN condition on Time to the WHERE statement
func WhereTimeIn(vals ...time.Time) *Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newWhereIn("time", args...)
}

// WhereTimeBetween adds a BETWEEN condition on Time to the WHERE statement
func WhereTimeBetween(low, high time.Time) *Where {
	return newWhereBetween("time", low, high)
}

// WhereSelect adds a condition on Select to the WHERE statement
func WhereSelect(op Op, val int) *Where {
	return newWhere(op, "select", val)
}

// WhereSelectIn adds an IN condition on Select to the WHERE statement
func WhereSelectIn(vals ...int) *Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newWhereIn("select", args...)
}

// WhereSelectBetween adds a BETWEEN condition on Select to the WHERE statement
func WhereSelectBetween(low, high int) *Where {
	return newWhereBetween("select", low, high)
}
