// Package personorm was auto-generated by github.com/posener/orm; DO NOT EDIT
package personorm

import (
	"github.com/posener/orm/example"
)

// API is the interface of the ORM object
type API interface {
	Close() error
	Create() *CreateBuilder
	Select() *SelectBuilder
	Insert() *InsertBuilder
	Update() *UpdateBuilder
	Delete() *DeleteBuilder
	InsertPerson(*example.Person) *InsertBuilder
	UpdatePerson(*example.Person) *UpdateBuilder

	Logger(Logger)
}

// Querier is the interface for a SELECT SQL statement
type Querier interface {
	Query() ([]example.Person, error)
}

// Counter is the interface for a SELECT SQL statement for counting purposes
type Counter interface {
	Count() ([]PersonCount, error)
}
