// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personorm

type columns struct {
	SelectName bool
	SelectAge  bool

	count bool // used for sql COUNT(*) column
}

// String is the SQL representation of columns
func (c columns) String() string {
	var s string
	if c.SelectName {
		s += "`name`, "
	}
	if c.SelectAge {
		s += "`age`, "
	}

	if c.count {
		s += "COUNT(*), "
	}
	if len(s) == 0 { // no specific column was selected
		return "*"
	}
	return s[:len(s)-2]
}

// selectAll returns true if no column was specifically selected
func (c *columns) selectAll() bool {
	return !c.SelectName && !c.SelectAge && !c.count
}
