// Autogenerated by github.com/posener/orm
package personorm

import (
	"database/sql"
	"log"
)

// Create creates a table for Person
func Create(db *sql.DB) error {
	// Create statement has a line for each variable with it's name and it's type.
	// The if statement is to remove the comma from the last line.
	stmt := `CREATE TABLE person (
		name VARCHAR(255),
		age INT
	)`
	log.Printf("Create: '%v'", stmt)
	_, err := db.Exec(stmt)
	return err
}
