// Autogenerated by github.com/posener/orm
package personorm

func (c TCreate) String() string {
	// Create statement has a line for each variable with it's name and it's type.
	return `CREATE TABLE person (
		name VARCHAR(255),
		age INT
	)`
}
