// Autogenerated by github.com/posener/orm
package personorm

import (
	"database/sql"
	"fmt"
	"log"
	"strings"

	"github.com/posener/orm/example"
)

func (i Insert) Person(p *example.Person) Insert {
	var j = i
	j = j.add("name", p.Name)
	j = j.add("age", p.Age)
	return j
}

func (i Insert) Name(value string) Insert {
	return i.add("name", value)
}

func (i Insert) Age(value int) Insert {
	return i.add("age", value)
}

// Create creates a table for Person
func (i Insert) Exec(db *sql.DB) error {
	if len(i.cols) == 0 || len(i.values) == 0 {
		return fmt.Errorf("nothing to insert")
	}
	stmt := fmt.Sprintf(`INSERT INTO person (%s) VALUES (%s)`,
		strings.Join(i.cols, ", "),
		qMarks(len(i.values)),
	)

	log.Printf("Insert: '%v' (%v)", stmt, i.values)
	_, err := db.Exec(stmt, i.values...)
	return err
}
