// Autogenerated by github.com/posener/orm
package personorm

import "github.com/posener/orm/example"

func (i Insert) Name(value string) Insert {
	return i.add("name", value)
}

func (i Insert) Age(value int) Insert {
	return i.add("age", value)
}

func (i Insert) Person(p *example.Person) Insert {
	var j = i
	j = j.add("name", p.Name)
	j = j.add("age", p.Age)
	return j
}
