// Autogenerated by github.com/posener/orm
package personorm

import "github.com/posener/orm/example"

type API interface {
	Create() *TCreate
	Query() *Select
	Insert() *TInsert
	Update() *TUpdate
	Delete() *TDelete
	InsertPerson(*example.Person) *TInsert
	UpdatePerson(*example.Person) *TUpdate
}
