// Autogenerated by github.com/posener/orm; DO NOT EDIT
package personorm

import (
	"fmt"

	"github.com/posener/orm/example"
)

func (u *TUpdate) String() string {
	return fmt.Sprintf(`UPDATE 'person' SET %s %s`,
		u.assignmentList(),
		u.where.String(),
	)
}

// InsertPerson creates an UPDATE statement according to the given object
func (o *ORM) UpdatePerson(p *example.Person) *TUpdate {
	u := o.Update()
	u.add("name", p.Name)
	u.add("age", p.Age)
	return u
}

// SetName sets value for column name in the UPDATE statement
func (u *TUpdate) SetName(value string) *TUpdate {
	return u.add("name", value)
}

// SetAge sets value for column age in the UPDATE statement
func (u *TUpdate) SetAge(value int) *TUpdate {
	return u.add("age", value)
}
