// Autogenerated by github.com/posener/orm
package personorm

// WhereName adds a condition on Name to the WHERE statement
func WhereName(op Op, val string) *Where {
	return newWhere(op, "name", val)
}

// WhereNameIn adds an IN condition on Name to the WHERE statement
func WhereNameIn(vals ...string) *Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newMulWhere(OpIn, "name", args...)
}

// WhereNameBetween adds a BETWEEN condition on Name to the WHERE statement
func WhereNameBetween(low, high string) *Where {
	return newMulWhere(OpBetween, "name", low, high)
}

// WhereAge adds a condition on Age to the WHERE statement
func WhereAge(op Op, val int) *Where {
	return newWhere(op, "age", val)
}

// WhereAgeIn adds an IN condition on Age to the WHERE statement
func WhereAgeIn(vals ...int) *Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newMulWhere(OpIn, "age", args...)
}

// WhereAgeBetween adds a BETWEEN condition on Age to the WHERE statement
func WhereAgeBetween(low, high int) *Where {
	return newMulWhere(OpBetween, "age", low, high)
}
