// Autogenerated by github.com/posener/orm
package personorm

func WhereName(op Op, val string) Where {
	return newWhere(op, "name", val)
}

func WhereNameIn(vals ...string) Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newMulWhere(OpIn, "name", args...)
}

func WhereNameBetween(low, high string) Where {
	return newMulWhere(OpBetween, "name", low, high)
}

func WhereAge(op Op, val int) Where {
	return newWhere(op, "age", val)
}

func WhereAgeIn(vals ...int) Where {
	args := make([]interface{}, len(vals))
	for i := range vals {
		args[i] = vals[i]
	}
	return newMulWhere(OpIn, "age", args...)
}

func WhereAgeBetween(low, high int) Where {
	return newMulWhere(OpBetween, "age", low, high)
}
